apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: xxxx # Replace with base64 encoded Docker config JSON containing GitHub Container Registry credentials