version: "3.8"

services:
  name-service:
    image: <aws-account-id>.dkr.ecr.us-<region>.amazonaws.com/<repository-name>:image-name-service # replace with your actual image URI
    container_name: image-name-container
    restart: always
    env_file:
      - /home/ubuntu/.config/service-envs/name-service/.env # host path to the .env file
    volumes:
      - /home/ubuntu/.config/mount-file/keyToMount:/usr/src/app/keyToMount # host path to the file to be mounted in the container
    ports:
      - "<host-port>:<container-port>"
    networks:
      - <network-name>
    deploy:
      resources:
        limits:
          memory: 1g
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:<container-port>/v1/health"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 10s

networks:
  <network-name>:
    external: true