apiVersion: v2
name: nodejs-api
description: A Helm chart for Node.js Express API deployment
type: application
version: 1.0.0
appVersion: "latest"
maintainers:
  - name: karosi12
    email: adekayor@gmail.com
